body:
  - type: textarea
    attributes:
      label: 📣 Related Issue
      description: 관련 이슈를 적어주세요.
      value: close #
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📝 Summary
      description: 해당 PR의 주요 작업 내용을 적어주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙏 Question & PR point
      description: PR과정에서 다른 팀원이 알아야할 사항이나 궁금증을 적어주세요.
  - type: textarea
    attributes:
      label: 📬 Reference
      description: 참고한 코드의 출처를 작성해주세요.
